version: '3.5'

services:
  api:
    build: .
    container_name: node-express-service
    image: andspuds/customer-api
    ports:
      - "8080:8080"
    networks:
      - overlay
    environment:
      - ENVIRONMENT=${ENVIRONMENT}

networks:
  overlay:
